In [2]:
import numpy as np

rng = np.random.default_rng(616)

price = (rng.random(10) * 10).round(2)

price

array([3.97, 8.66, 4.6 , 3.06, 5.74, 0.89, 8.82, 7.32, 7.32, 5.62])

In [ ]:
# array.mean() returns the average of the values in an array(ortalam)
# sales_array.sum() returns the sum of all values in an array(toplama)
# array.max() returns the largest value in an array(en büyüğünü seçme)
# array.min() minimum

In [ ]:
# array.sum() returns the sum of all values in an array (hepsini toplar)
# array.sum(axis=0) aggregates across rows (düzlemdekileri toplar)
# array.sum(axis=1) ayrı ayrı toplar

In [3]:
inventory = rng.integers(0, 100, 10)
inventory

array([80, 33, 60,  6, 31, 35, 16, 20, 29, 43], dtype=int64)

In [4]:
price.mean()

5.6

In [5]:
inventory.mean()

35.3

In [6]:
inventory.sum()

353

In [7]:
inventory.std() #standart sapması

20.48438429633656

In [12]:
(price * inventory).argmax() # bir hedef işlevden maksimum değeri veren bağımsız değişkeni bulan bir işlemdir.

0

In [13]:
price_2d = price.reshape(5, 2)

In [14]:
price_2d

array([[3.97, 8.66],
       [4.6 , 3.06],
       [5.74, 0.89],
       [8.82, 7.32],
       [7.32, 5.62]])

In [16]:
price_2d.mean(axis=0)

array([6.09, 5.11])