In [34]:
import numpy as np

rng = np.random.default_rng(616)

inventory = rng.integers(0, 100, 10)

inventory

array([39, 39, 93, 86, 48, 46, 48, 30, 11, 57], dtype=int64)

In [35]:
inventory - 24 

array([ 15,  15,  69,  62,  24,  22,  24,   6, -13,  33], dtype=int64)

In [36]:
(inventory / 2).dtype

dtype('float64')

In [37]:
price = (rng.random(10) * 10).round(2)

price

array([0.89, 8.82, 7.32, 7.32, 5.62, 3.4 , 0.63, 3.57, 2.03, 4.31])

In [38]:
(price * inventory).sum()

2520.4700000000003

In [39]:
inventory_list = list(inventory)

In [40]:
inventory_list

[39, 39, 93, 86, 48, 46, 48, 30, 11, 57]

In [44]:
new_inventory = []

for x in inventory_list:
    new_inventory.append(x + 2)

new_inventory

[41, 41, 95, 88, 50, 48, 50, 32, 13, 59]

In [48]:
[x + 2 for x in inventory_list]

[41, 41, 95, 88, 50, 48, 50, 32, 13, 59]

In [50]:
[x * y for x, y in zip(inventory_list, price)]

[34.71,
 343.98,
 680.76,
 629.52,
 269.76,
 156.4,
 30.240000000000002,
 107.1,
 22.33,
 245.67]