In [1]:
import numpy as np

In [2]:
#sales_array_sort() axis=1 by default which sorts a two dimensional array row by row
#sales_array.sort(axis=0) axis=0 will sort by columns

In [3]:
product_value = np.array([205.4 , 158.4, 138.4, 186.4, 6.24, 202.92, 106.44, 3.68, 26.15, 403.2])

product_value

array([205.4 , 158.4 , 138.4 , 186.4 ,   6.24, 202.92, 106.44,   3.68,
        26.15, 403.2 ])

In [4]:
np.sort(product_value)

array([  3.68,   6.24,  26.15, 106.44, 138.4 , 158.4 , 186.4 , 202.92,
       205.4 , 403.2 ])

In [5]:
product_value

array([205.4 , 158.4 , 138.4 , 186.4 ,   6.24, 202.92, 106.44,   3.68,
        26.15, 403.2 ])

In [6]:
product_value.sort()

In [8]:
product_value[0]

3.68

In [10]:
product_value[-1]

403.2

In [11]:
product_value[::-1]

array([403.2 , 205.4 , 202.92, 186.4 , 158.4 , 138.4 , 106.44,  26.15,
         6.24,   3.68])